# Use an official Python runtime as the base image
FROM python:3.12-slim

# Set the working directory in the container
WORKDIR /app

# Copy the server Python script into the container
COPY server.py /app/server.py

# Expose port 8888 for the server to listen on
EXPOSE 8888

# Run the server script when the container starts
CMD ["python", "server.py"]